let _calcSettings={}, _calcRolls=[], _calcPrinters=[];
pageRenderers.calculadora=async function(){[_calcSettings,_calcRolls,_calcPrinters]=await Promise.all([API.get('/settings'),API.get('/rolls'),API.get('/printers')]);renderCalculadora();calcStandalone();};
function renderCalculadora(){R('content').innerHTML=`<div class="row"><div class="col"><div class="table-wrap" style="padding:1.25rem"><h3 class="section-title">🧮 Calculadora de custos e preço</h3><div class="form-grid">
<div class="form-group"><label>Quantidade</label><input type="number" id="cc-qty" value="1" min="1" oninput="calcStandalone()"></div>
<div class="form-group"><label>Peso por peça (g)</label><input type="number" id="cc-weight" value="0" step="0.1" min="0" oninput="calcStandalone()"></div>
<div class="form-group"><label>Tempo por peça (min)</label><input type="number" id="cc-time" value="0" step="1" min="0" oninput="calcStandalone()"></div>
<div class="form-group"><label>Tempo de desenvolvimento (min)</label><input type="number" id="cc-project" value="0" step="1" min="0" oninput="calcStandalone()"></div>
<div class="form-group"><label>Rolo</label><select id="cc-roll" onchange="calcStandalone()"><option value="">Sem rolo</option>${_calcRolls.map(r=>`<option value="${r.id}">${r.type} ${r.color||''} — R$ ${Number(r.cost_per_gram||0).toFixed(4)}/g</option>`).join('')}</select></div>
<div class="form-group"><label>Impressora</label><select id="cc-printer" onchange="calcStandalone()"><option value="">Sem impressora</option>${_calcPrinters.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div>
<div class="form-group"><label>Horas extras de mão de obra</label><input type="number" id="cc-labor" value="0" step="0.01" min="0" oninput="calcStandalone()"></div>
<div class="form-group"><label>Outros custos (R$)</label><input type="number" id="cc-other" value="0" step="0.01" min="0" oninput="calcStandalone()"></div>
<div class="form-group"><label>Modo de preço</label><select id="cc-mode" onchange="calcStandalone()"><option value="markup">Markup</option><option value="direct">Preço direto</option></select></div>
<div class="form-group" id="cc-markup-wrap"><label>Markup (%)</label><input type="number" id="cc-markup" value="40" step="0.01" min="0" oninput="calcStandalone()"></div>
<div class="form-group" id="cc-direct-wrap" style="display:none"><label>Preço direto (R$)</label><input type="number" id="cc-direct" value="0" step="0.01" min="0" oninput="calcStandalone()"></div>
</div><div class="calc-box"><div class="calc-row"><span>Material</span><strong id="cc-material">R$ 0,00</strong></div><div class="calc-row"><span>Energia</span><strong id="cc-energy">R$ 0,00</strong></div><div class="calc-row"><span>Máquina</span><strong id="cc-machine">R$ 0,00</strong></div><div class="calc-row"><span>Manutenção</span><strong id="cc-maintenance">R$ 0,00</strong></div><div class="calc-row"><span>Mão de obra</span><strong id="cc-labor-total">R$ 0,00</strong></div><div class="calc-row"><span>Outros</span><strong id="cc-other-total">R$ 0,00</strong></div><div class="calc-row total"><span>Custo total</span><strong id="cc-total">R$ 0,00</strong></div><div class="calc-row profit"><span>Lucro</span><strong id="cc-profit">R$ 0,00</strong></div><div class="calc-row"><span>Margem</span><strong id="cc-margin">0,00%</strong></div><div class="calc-row"><span>Markup real</span><strong id="cc-real-markup">0,00%</strong></div><div class="calc-row total"><span>Preço final</span><strong id="cc-price">R$ 0,00</strong></div></div></div></div>`}
function calcStandalone(){const $=id=>R(id);if(!$('cc-qty'))return;const qty=Math.max(1,Number($('cc-qty').value)||1),weight=Math.max(0,Number($('cc-weight').value)||0),time=Math.max(0,Number($('cc-time').value)||0),project=Math.max(0,Number($('cc-project').value)||0),roll=_calcRolls.find(r=>String(r.id)===String($('cc-roll').value)),printer=_calcPrinters.find(p=>String(p.id)===String($('cc-printer').value)),hours=time*qty/60,material=weight*qty*Number(roll?.cost_per_gram||0),energy=printer?(Number(printer.power_watts||0)/1000)*hours*Number(_calcSettings.energy_cost_kwh||0):0,machine=hours*Number(_calcSettings.machine_cost_hour||0),maintenance=hours*Number(_calcSettings.maintenance_cost_hour||0),labor=(project/60)*Number(_calcSettings.labor_cost_hour||0)+Math.max(0,Number($('cc-labor').value)||0),other=Math.max(0,Number($('cc-other').value)||0),total=material+energy+machine+maintenance+labor+other,mode=$('cc-mode').value,markup=Math.max(0,Number($('cc-markup').value)||0),price=mode==='direct'?Math.max(0,Number($('cc-direct').value)||0):total*(1+markup/100),profit=price-total,margin=price?profit/price*100:0,realMarkup=total?profit/total*100:0;const set=(id,v)=>$(id).textContent=money(v);set('cc-material',material);set('cc-energy',energy);set('cc-machine',machine);set('cc-maintenance',maintenance);set('cc-labor-total',labor);set('cc-other-total',other);set('cc-total',total);set('cc-profit',profit);set('cc-price',price);$('cc-margin').textContent=margin.toFixed(2)+'%';$('cc-real-markup').textContent=realMarkup.toFixed(2)+'%';$('cc-markup-wrap').style.display=mode==='markup'?'':'none';$('cc-direct-wrap').style.display=mode==='direct'?'':'none';}
window.calcStandalone=calcStandalone;
