let _tools=[];
pageRenderers.ferramentas=async()=>{_tools=await API.get('/consumables');renderFerramentas()};
function renderFerramentas(filter=''){
 const list=filter?_tools.filter(x=>(x.name+' '+(x.category||'')).toLowerCase().includes(filter)):_tools;
 R('content').innerHTML=`<div class="table-wrap"><div class="table-header"><input class="search-input" placeholder="🔍 Buscar..." oninput="renderFerramentas(this.value.toLowerCase())"><button class="btn btn-primary" onclick="openFerramentaModal()">+ Novo Consumível</button></div><table><thead><tr><th>Item</th><th>Categoria</th><th>Qtd.</th><th>Mínimo</th><th>Custo/un</th><th>Status</th><th></th></tr></thead><tbody>${list.length?list.map(x=>`<tr style="${x.current_qty<=x.min_qty?'background:rgba(245,158,11,.07)':''}"><td><strong>${x.name}</strong>${x.photo_url?`<br><img src="${x.photo_url}" style="width:48px;height:48px;object-fit:cover;border-radius:6px;margin-top:4px">`:''}</td><td>${x.category||'—'}</td><td>${num(x.current_qty,2)} ${x.unit}</td><td>${num(x.min_qty,2)}</td><td>${money(x.unit_cost)}</td><td>${x.current_qty<=x.min_qty?badge('ESTOQUE_BAIXO'):badge('DISPONIVEL')}</td><td><div class="actions"><button class="btn btn-secondary btn-sm" onclick="openFerramentaModal(${x.id})">✏️</button><button class="btn btn-secondary btn-sm" onclick="openToolMov(${x.id},'${x.name.replaceAll("'","\\'")}')">↕️</button><button class="btn btn-danger btn-sm" onclick="deleteFerramenta(${x.id})">🗑️</button></div></td></tr>`).join(''):'<tr><td colspan="7" style="text-align:center;padding:2rem;color:var(--text2)">Nenhum item cadastrado.</td></tr>'}</tbody></table></div>`;
}
function openFerramentaModal(id){const x=id?_tools.find(v=>v.id===id):{};openModal(id?'Editar Consumível':'Novo Consumível',`<div class="form-grid"><div class="form-group span2"><label>Nome *</label><input id="tf-name" value="${x.name||''}"></div><div class="form-group"><label>Categoria</label><input id="tf-category" value="${x.category||''}"></div><div class="form-group"><label>Unidade</label><select id="tf-unit"><option value="un">Unidade (un)</option><option value="mL">Mililitro (mL)</option><option value="L">Litro (L)</option><option value="g">Grama (g)</option><option value="kg">Quilograma (kg)</option><option value="m">Metro (m)</option><option value="cm">Centímetro (cm)</option></select></div><div class="form-group"><label>Quantidade atual</label><input type="number" id="tf-current_qty" value="${x.current_qty||0}" step="0.01"></div><div class="form-group"><label>Mínimo</label><input type="number" id="tf-min_qty" value="${x.min_qty||0}" step="0.01"></div><div class="form-group"><label>Custo por unidade</label><input type="number" id="tf-unit_cost" value="${x.unit_cost||0}" step="0.0001"></div><div class="form-group"><label>Fornecedor</label><input id="tf-supplier" value="${x.supplier||''}"></div><div class="form-group span2"><label>Foto</label><input type="file" id="tf-photo" accept="image/*"><small style="color:var(--text2)">PNG/JPG/WebP até 8 MB.</small></div><div class="form-group span2"><label>Observações</label><textarea id="tf-notes">${x.notes||''}</textarea></div></div>${x.photo_url?`<img src="${x.photo_url}" style="width:100%;max-height:180px;object-fit:contain;border-radius:8px;margin-top:1rem">`:''}`,`<button class="btn btn-secondary" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="saveFerramenta(${id||0})">Salvar</button>`);setTimeout(()=>{if(R('tf-unit'))R('tf-unit').value=x.unit||'un'},0)}
async function saveFerramenta(id){const b={name:R('tf-name').value,category:R('tf-category').value,unit:R('tf-unit').value,current_qty:R('tf-current_qty').value,min_qty:R('tf-min_qty').value,unit_cost:R('tf-unit_cost').value,supplier:R('tf-supplier').value,notes:R('tf-notes').value};if(!b.name)return toast('Nome é obrigatório','err');try{const r=id?await API.put(`/consumables/${id}`,b):await API.post('/consumables',b);const itemId=id||r.id;const file=R('tf-photo').files[0];if(file)await API.upload(`/uploads/consumables/${itemId}`,file);closeModal();toast('Salvo!');pageRenderers.ferramentas()}catch(e){toast(e.message,'err')}}
async function deleteFerramenta(id){if(!confirmAction('Excluir este item?'))return;try{await API.del(`/consumables/${id}`);pageRenderers.ferramentas()}catch(e){toast(e.message,'err')}}
function openToolMov(id,name){openModal(`Movimentação — ${name}`,`<div class="form-grid"><div class="form-group"><label>Tipo</label><select id="tm-type"><option value="ENTRADA">Entrada</option><option value="SAIDA">Saída</option><option value="DEVOLUCAO">Devolução</option></select></div><div class="form-group"><label>Quantidade</label><input type="number" id="tm-qty" value="1" step="0.01"></div><div class="form-group span2"><label>Motivo</label><input id="tm-reason" value="AJUSTE"></div><div class="form-group span2"><label>Observações</label><textarea id="tm-notes"></textarea></div></div>`,`<button class="btn btn-secondary" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="saveToolMov(${id})">Registrar</button>`)}
async function saveToolMov(id){try{await API.post(`/consumables/${id}/movement`,{type:R('tm-type').value,quantity:R('tm-qty').value,reason:R('tm-reason').value,notes:R('tm-notes').value});closeModal();toast('Movimentação registrada');pageRenderers.ferramentas()}catch(e){toast(e.message,'err')}}

window.openFerramentaModal=openFerramentaModal;window.saveFerramenta=saveFerramenta;window.deleteFerramenta=deleteFerramenta;window.openToolMov=openToolMov;window.saveToolMov=saveToolMov;
