let _quotes=[], _quoteCustomers=[], _quoteProducts=[], _quoteRolls=[], _quotePrinters=[], _quoteProjects=[], _quoteSettings={};

pageRenderers.orcamentos = async function(){
  [_quotes,_quoteCustomers,_quoteProducts,_quoteRolls,_quotePrinters,_quoteProjects,_quoteSettings] = await Promise.all([
    API.get('/quotes'), API.get('/customers'), API.get('/products'), API.get('/rolls'), API.get('/printers'), API.get('/projects'), API.get('/settings')
  ]);
  renderOrcamentos();
};

function renderOrcamentos(){
  R('content').innerHTML=`
    <div class="table-wrap">
      <div class="table-header">
        <input class="search-input" placeholder="🔍 Buscar cliente ou produto..." oninput="filterOrcamentos(this.value.toLowerCase())">
        <button class="btn btn-primary" onclick="openOrcamentoModal()">+ Novo Orçamento</button>
      </div>
      <table><thead><tr><th>#</th><th>Cliente</th><th>Produto</th><th>Data</th><th>Qtd</th><th>Custo</th><th>Preço</th><th>Status</th><th></th></tr></thead>
      <tbody id="quotes-body">${quoteRows(_quotes)}</tbody></table>
    </div>`;
}
function quoteRows(list){return list.length?list.map(q=>`<tr><td>#${q.id}</td><td><strong>${g3dEscape(q.customer_name||'—')}</strong></td><td>${g3dEscape(q.product_description||q.product_name||'—')}</td><td>${dateStr(q.created_at)}</td><td>${q.quantity}</td><td>${money(q.cost_total)}</td><td><strong>${money(q.price_total)}</strong></td><td>${badge(q.status)}</td><td><div class="actions"><button class="btn btn-secondary btn-sm" onclick="viewOrcamento(${q.id})">👁️</button><button class="btn btn-secondary btn-sm" onclick="openOrcamentoModal(${q.id})">✏️</button><button class="btn btn-secondary btn-sm" onclick="duplicateOrcamento(${q.id})">📄</button><button class="btn btn-danger btn-sm" onclick="deleteOrcamento(${q.id})">🗑️</button></div></td></tr>`).join(''):'<tr><td colspan="9" style="text-align:center;color:var(--text2);padding:2rem">Nenhum orçamento salvo</td></tr>'}
function filterOrcamentos(f){const l=_quotes.filter(q=>(q.customer_name||'').toLowerCase().includes(f)||(q.product_description||'').toLowerCase().includes(f));R('quotes-body').innerHTML=quoteRows(l)}

function quoteForm(q={}){
 const materialLabel=r=>`${r.type}${r.brand?' — '+r.brand:''}${r.color?' — '+r.color:''}${r.code?' ['+r.code+']':''} — ${money(r.cost_per_gram)}/g`;
 return `<div class="form-grid">
  <div class="form-group"><label>Cliente (opcional)</label><select id="q-customer_id"><option value="">Nenhum</option>${_quoteCustomers.map(c=>`<option value="${c.id}" ${q.customer_id==c.id?'selected':''}>${g3dEscape(c.name)}</option>`).join('')}</select></div>
  <div class="form-group"><label>Projeto (opcional)</label><select id="q-project_id"><option value="">Nenhum</option>${_quoteProjects.map(pr=>`<option value="${pr.id}" ${q.project_id==pr.id?'selected':''}>${g3dEscape(pr.name)}</option>`).join('')}</select></div><div class="form-group"><label>Produto cadastrado</label><select id="q-product_id" onchange="autofillQuoteProduct()"><option value="">Nenhum / personalizado</option>${_quoteProducts.map(p=>`<option value="${p.id}" ${q.product_id==p.id?'selected':''}>${g3dEscape(p.name)}</option>`).join('')}</select></div><div class="form-group"><label>Produto / descrição (opcional)</label><input id="q-description" value="${g3dEscape(q.product_description||q.product_name||'')}"></div>
  <div class="form-group"><label>Quantidade</label><input type="number" id="q-quantity" min="1" value="${q.quantity||1}" oninput="calcOrcamento()"></div>
  <div class="form-group"><label>Material / rolo</label><select id="q-roll_id" onchange="calcOrcamento()"><option value="">Sem custo de material</option>${_quoteRolls.map(r=>`<option value="${r.id}" ${q.roll_id==r.id?'selected':''}>${g3dEscape(materialLabel(r))}</option>`).join('')}</select></div>
  <div class="form-group"><label>Peso por unidade (g)</label><input type="number" id="q-weight_g" min="0" step="0.01" value="${q.weight_g||0}" oninput="calcOrcamento()"></div>
  <div class="form-group"><label>Tempo de impressão por unidade</label><input id="q-time" placeholder="ex.: 2h 30min" value="${formatMinutes(q.print_time_min)}" oninput="calcOrcamento()"></div>
  <div class="form-group span2"><label>Impressora (opcional)</label><select id="q-printer_id" onchange="calcOrcamento()"><option value="">Nenhuma</option>${_quotePrinters.map(p=>`<option value="${p.id}" ${q.printer_id==p.id?'selected':''}>${g3dEscape(p.name)}${Number(p.power_watts)>0?' — '+p.power_watts+' W':''}</option>`).join('')}</select></div>
  <div class="form-group"><label>Horas de projeto</label><input id="q-project-time" placeholder="ex.: 1h 30min" value="${formatMinutes(q.project_time_min)}" oninput="calcOrcamento()"></div><div class="form-group"><label>Mão de obra extra (R$)</label><input type="number" id="q-labor" min="0" step="0.01" value="${Math.max(0,Number(q.labor_cost||0)-(Number(q.project_time_min||0)/60*(Number(_quoteSettings.labor_cost_hour)||0))).toFixed(2)}" oninput="calcOrcamento()"></div>
  <div class="form-group"><label>Outros custos (total, R$)</label><input type="number" id="q-other" min="0" step="0.01" value="${q.other_costs||0}" oninput="calcOrcamento()"></div>
  <div class="form-group"><label>Modo de preço</label><select id="q-price_mode" onchange="togglePriceMode()"><option value="markup" ${q.price_mode!=='direct'?'selected':''}>Markup sobre custo</option><option value="direct" ${q.price_mode==='direct'?'selected':''}>Preço final direto</option></select></div>
  <div class="form-group" id="q-markup-wrap"><label>Markup (%)</label><input type="number" id="q-markup" min="0" step="0.01" value="${q.markup_percent??40}" oninput="calcOrcamento()"></div>
  <div class="form-group" id="q-direct-wrap" style="display:none"><label>Preço final (R$)</label><input type="number" id="q-direct" min="0" step="0.01" value="${q.price_total||0}" oninput="calcOrcamento('direct')"></div>
  <div class="form-group span2"><label>Observações</label><textarea id="q-notes">${g3dEscape(q.notes||'')}</textarea></div>
 </div>
 <div class="calc-box" style="margin-top:1rem"><div class="calc-row"><span>Filamento</span><strong id="q-cost-material">R$ 0,00</strong></div><div class="calc-row"><span>Energia</span><strong id="q-cost-energy">R$ 0,00</strong></div><div class="calc-row"><span>Máquina</span><strong id="q-cost-machine">R$ 0,00</strong></div><div class="calc-row"><span>Manutenção</span><strong id="q-cost-maintenance">R$ 0,00</strong></div><div class="calc-row"><span>Mão de obra</span><strong id="q-cost-labor">R$ 0,00</strong></div><div class="calc-row"><span>Outros</span><strong id="q-cost-other">R$ 0,00</strong></div><div class="calc-row total"><span>Custo total</span><strong id="q-cost-total">R$ 0,00</strong></div><div class="calc-row"><span>Lucro</span><strong id="q-profit">R$ 0,00</strong></div><div class="calc-row total"><span>Preço final</span><strong id="q-price">R$ 0,00</strong></div><div class="calc-row"><span>Margem real sobre venda</span><strong id="q-real-margin">0,00%</strong></div></div>`;
}
function autofillQuoteProduct(){const p=_quoteProducts.find(x=>x.id==R('q-product_id')?.value);if(p&&!R('q-description').value)R('q-description').value=p.name;calcOrcamento()}
function viewOrcamento(id){const q=_quotes.find(x=>x.id===id);if(!q)return;openModal('Orçamento #'+q.id,`<div class="calc-box"><div class="calc-row"><span>Cliente</span><strong>${g3dEscape(q.customer_name||'—')}</strong></div><div class="calc-row"><span>Projeto</span><strong>${g3dEscape(q.project_name||'—')}</strong></div><div class="calc-row"><span>Produto</span><strong>${g3dEscape(q.product_description||q.product_name||'—')}</strong></div><div class="calc-row"><span>Quantidade</span><strong>${q.quantity}</strong></div><div class="calc-row"><span>Material</span><strong>${g3dEscape((q.material_type||'—')+(q.material_color?' '+q.material_color:''))}</strong></div><div class="calc-row"><span>Peso total</span><strong>${num(Number(q.weight_g)*Number(q.quantity),2)} g</strong></div><div class="calc-row"><span>Horas de projeto</span><strong>${formatMinutes(q.project_time_min)}</strong></div><div class="calc-row"><span>Tempo total de impressão</span><strong>${formatMinutes(Number(q.print_time_min)*Number(q.quantity))}</strong></div><div class="calc-row"><span>Custo total</span><strong>${money(q.cost_total)}</strong></div><div class="calc-row"><span>Lucro</span><strong>${money(q.profit)}</strong></div><div class="calc-row total"><span>Preço final</span><strong>${money(q.price_total)}</strong></div></div>`,`<button class="btn btn-secondary" onclick="copySavedQuote(${q.id})">📋 Copiar</button><button class="btn btn-secondary" onclick="closeModal()">Fechar</button>`,false)}
async function copySavedQuote(id){const q=_quotes.find(x=>x.id===id);if(!q)return;const text=`ORÇAMENTO - GESTÃO 3D\n\nCliente: ${q.customer_name||'—'}\nProduto: ${q.product_description||q.product_name||'—'}\nQuantidade: ${q.quantity}\nMaterial: ${q.material_type||'—'}\nPeso: ${num(q.weight_g,2)} g/un.\nTempo de impressão: ${formatMinutes(q.print_time_min)} /un.\n\nCusto total: ${money(q.cost_total)}\nPreço final: ${money(q.price_total)}\nLucro: ${money(q.profit)}`;try{await navigator.clipboard.writeText(text);toast('Orçamento copiado!')}catch{toast('Não foi possível copiar','err')}}
function openOrcamentoModal(id){const q=id?_quotes.find(x=>x.id===id):{};openModal(id?'Editar Orçamento':'Novo Orçamento',quoteForm(q),`<button class="btn btn-secondary" onclick="closeModal()">Cancelar</button><button class="btn btn-secondary" onclick="copyCurrentQuote()">📋 Copiar</button><button class="btn btn-secondary" onclick="whatsappCurrentQuote()">💬 WhatsApp</button><button class="btn btn-primary" onclick="saveOrcamento(${id||0})">💾 Salvar</button>`,true);setTimeout(()=>{ if(R('q-price_mode')) R('q-price_mode').value=q.price_mode||'markup'; togglePriceMode(); calcOrcamento(); },0)}
function parseTime(v){v=String(v||'').trim().toLowerCase();if(!v)return 0;const h=v.match(/(\d+(?:[.,]\d+)?)\s*h/),m=v.match(/(\d+(?:[.,]\d+)?)\s*m/);if(h||m)return (h?parseFloat(h[1].replace(',','.'))*60:0)+(m?parseFloat(m[1].replace(',','.')):0);const n=Number(v.replace(',','.'));return Number.isFinite(n)?n:0}
function formatMinutes(v){v=Number(v)||0;const h=Math.floor(v/60),m=Math.round(v%60);return h?`${h}h ${m?m+'min':''}`.trim():(m?`${m}min`:'')}
function calcData(mode){mode=mode||R('q-price_mode')?.value||'markup';const qty=Math.max(1,Number(R('q-quantity')?.value)||1),weight=Math.max(0,Number(R('q-weight_g')?.value)||0),time=Math.max(0,parseTime(R('q-time')?.value)),projectTime=Math.max(0,parseTime(R('q-project-time')?.value)),hours=time*qty/60;const roll=_quoteRolls.find(x=>x.id==R('q-roll_id')?.value),printer=_quotePrinters.find(x=>x.id==R('q-printer_id')?.value);const material=weight*qty*(roll?Number(roll.cost_per_gram)||0:0),laborExtra=Math.max(0,Number(R('q-labor')?.value)||0),laborRate=Number(_quoteSettings.labor_cost_hour)||0,labor=projectTime/60*laborRate+laborExtra;const energy=printer&&Number(printer.power_watts)>0?(Number(printer.power_watts)/1000)*hours*(Number(_quoteSettings.energy_cost_kwh)||0):0,machine=hours*(Number(_quoteSettings.machine_cost_hour)||0),maintenance=hours*(Number(_quoteSettings.maintenance_cost_hour)||0),other=Math.max(0,Number(R('q-other')?.value)||0),total=material+energy+machine+maintenance+labor+other;const markup=Math.max(0,Number(R('q-markup')?.value)||0);const price=mode==='direct'?Math.max(0,Number(R('q-direct')?.value)||0):total*(1+markup/100);return {qty,weight,time,projectTime,labor,laborExtra,other,material,energy,machine,maintenance,total,markup,price,profit:price-total,realMargin:price>0?(price-total)/price*100:0}}
function calcOrcamento(mode){const d=calcData(mode||R('q-price_mode')?.value);['material','energy','machine','maintenance','labor','other'].forEach(k=>{if(R('q-cost-'+k))R('q-cost-'+k).textContent=money(d[k])});R('q-cost-total').textContent=money(d.total);R('q-profit').textContent=money(d.profit);R('q-price').textContent=money(d.price);R('q-real-margin').textContent=num(d.realMargin,2)+'%'}
function togglePriceMode(){const direct=R('q-price_mode').value==='direct';R('q-markup-wrap').style.display=direct?'none':'block';R('q-direct-wrap').style.display=direct?'block':'none';calcOrcamento()}
function quoteText(){const d=calcData();const customer=R('q-customer_id').selectedOptions[0]?.text||'—',desc=R('q-description').value||'—',roll=_quoteRolls.find(x=>x.id==R('q-roll_id').value);return `ORÇAMENTO - GESTÃO 3D\n\nCliente: ${customer}\nProduto: ${desc}\nQuantidade: ${d.qty}\nMaterial: ${roll?roll.type+(roll.color?' '+roll.color:''):'—'}\nPeso: ${num(d.weight,2)} g/un.\nTempo de impressão: ${formatMinutes(d.time)} /un.\n\nCusto total: ${money(d.total)}\nPreço final: ${money(d.price)}\nLucro: ${money(d.profit)}`}
async function copyCurrentQuote(){try{await navigator.clipboard.writeText(quoteText());toast('Orçamento copiado!')}catch{toast('Não foi possível copiar','err')}}
function whatsappCurrentQuote(){const url='https://wa.me/?text='+encodeURIComponent(quoteText());window.open(url,'_blank','noopener,noreferrer')}
async function saveOrcamento(id){const d=calcData();const body={customer_id:R('q-customer_id').value||null,project_id:R('q-project_id').value||null,product_id:R('q-product_id').value||null,product_description:R('q-description').value.trim()||'Orçamento personalizado',quantity:d.qty,project_time_min:d.projectTime,roll_id:R('q-roll_id').value||null,printer_id:R('q-printer_id').value||null,weight_g:d.weight,print_time_min:d.time,labor_extra:d.laborExtra,other_costs:d.other,markup_percent:d.markup,price_total:d.price,price_mode:R('q-price_mode').value,status:R('q-status')?.value||'ORCAMENTO',notes:R('q-notes').value};try{if(id)await API.put(`/quotes/${id}`,body);else await API.post('/quotes',body);closeModal();toast('Orçamento salvo!');pageRenderers.orcamentos()}catch(e){toast(e.message,'err')}}
async function duplicateOrcamento(id){const q=_quotes.find(x=>x.id===id);if(!q)return;openOrcamentoModal();setTimeout(()=>{R('q-customer_id').value=q.customer_id||'';R('q-project_id').value=q.project_id||'';R('q-product_id').value=q.product_id||'';R('q-description').value=q.product_description||'';R('q-project-time').value=formatMinutes(q.project_time_min);R('q-quantity').value=q.quantity||1;R('q-roll_id').value=q.roll_id||'';R('q-printer_id').value=q.printer_id||'';R('q-weight_g').value=q.weight_g||0;R('q-time').value=formatMinutes(q.print_time_min);R('q-labor').value=Math.max(0,Number(q.labor_cost||0)-(Number(q.project_time_min||0)/60*(Number(_quoteSettings.labor_cost_hour)||0))).toFixed(2);R('q-other').value=q.other_costs||0;R('q-markup').value=q.markup_percent||0;R('q-direct').value=q.price_total||0;R('q-price_mode').value=q.price_mode||'markup';R('q-notes').value=q.notes||'';togglePriceMode();calcOrcamento()},0)}
async function deleteOrcamento(id){if(!confirmAction('Excluir este orçamento?'))return;try{await API.del(`/quotes/${id}`);toast('Orçamento excluído!');pageRenderers.orcamentos()}catch(e){toast(e.message,'err')}}

window.openOrcamentoModal=openOrcamentoModal;window.viewOrcamento=viewOrcamento;window.copySavedQuote=copySavedQuote;window.copyCurrentQuote=copyCurrentQuote;window.whatsappCurrentQuote=whatsappCurrentQuote;window.duplicateOrcamento=duplicateOrcamento;window.deleteOrcamento=deleteOrcamento;window.autofillQuoteProduct=autofillQuoteProduct;window.calcOrcamento=calcOrcamento;window.togglePriceMode=togglePriceMode;window.filterOrcamentos=filterOrcamentos;window.saveOrcamento=saveOrcamento;
