let _parts=[];
pageRenderers.pecas=async()=>{_parts=await API.get('/parts');renderPecas()};
function renderPecas(filter=''){const list=filter?_parts.filter(x=>(x.name+' '+(x.type||'')+' '+(x.size||'')+' '+(x.material||'')).toLowerCase().includes(filter)):_parts;R('content').innerHTML=`<div class="table-wrap"><div class="table-header"><input class="search-input" placeholder="🔍 Buscar peça, tipo ou tamanho..." oninput="renderPecas(this.value.toLowerCase())"><button class="btn btn-primary" onclick="openPecaModal()">+ Nova Peça</button></div><table><thead><tr><th>Peça</th><th>Tipo</th><th>Tamanho</th><th>Material</th><th>Qtd.</th><th>Mínimo</th><th>Custo/un</th><th></th></tr></thead><tbody>${list.length?list.map(x=>`<tr style="${x.current_qty<=x.min_qty?'background:rgba(245,158,11,.07)':''}"><td><strong>${x.name}</strong>${x.photo_url?`<br><img src="${x.photo_url}" style="width:48px;height:48px;object-fit:cover;border-radius:6px;margin-top:4px">`:''}</td><td>${x.type||'—'}</td><td>${x.size||'—'}</td><td>${x.material||'—'}</td><td>${num(x.current_qty,2)}</td><td>${num(x.min_qty,2)}</td><td>${money(x.unit_cost)}</td><td><div class="actions"><button class="btn btn-secondary btn-sm" onclick="openPecaModal(${x.id})">✏️</button><button class="btn btn-secondary btn-sm" onclick="openPecaMov(${x.id},'${x.name.replaceAll("'","\\'")}')">↕️</button><button class="btn btn-danger btn-sm" onclick="deletePeca(${x.id})">🗑️</button></div></td></tr>`).join(''):'<tr><td colspan="8" style="text-align:center;padding:2rem;color:var(--text2)">Nenhuma peça cadastrada.</td></tr>'}</tbody></table></div>`}
function openPecaModal(id){const x=id?_parts.find(v=>v.id===id):{};openModal(id?'Editar Peça':'Nova Peça',`<div class="form-grid"><div class="form-group span2"><label>Nome *</label><input id="pf-name2" value="${x.name||''}"></div><div class="form-group"><label>Categoria</label><input id="pf-category2" value="${x.category||''}"></div><div class="form-group"><label>Tipo</label><input id="pf-type2" value="${x.type||''}" placeholder="Parafuso, porca, bucha..."></div><div class="form-group"><label>Tamanho</label><input id="pf-size2" value="${x.size||''}" placeholder="M3x10, 608ZZ..."></div><div class="form-group"><label>Material</label><input id="pf-material2" value="${x.material||''}"></div><div class="form-group"><label>Quantidade atual</label><input type="number" id="pf-current2" value="${x.current_qty||0}" step="0.01"></div><div class="form-group"><label>Mínimo</label><input type="number" id="pf-min2" value="${x.min_qty||0}" step="0.01"></div><div class="form-group"><label>Custo/unidade</label><input type="number" id="pf-cost2" value="${x.unit_cost||0}" step="0.0001"></div><div class="form-group"><label>Fornecedor</label><input id="pf-supplier2" value="${x.supplier||''}"></div><div class="form-group span2"><label>Foto</label><input type="file" id="pf-photo2" accept="image/*"></div><div class="form-group span2"><label>Observações</label><textarea id="pf-notes2">${x.notes||''}</textarea></div></div>${x.photo_url?`<img src="${x.photo_url}" style="width:100%;max-height:180px;object-fit:contain;border-radius:8px;margin-top:1rem">`:''}`,`<button class="btn btn-secondary" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="savePeca(${id||0})">Salvar</button>`)}
async function savePeca(id){const b={name:R('pf-name2').value,category:R('pf-category2').value,type:R('pf-type2').value,size:R('pf-size2').value,material:R('pf-material2').value,current_qty:R('pf-current2').value,min_qty:R('pf-min2').value,unit_cost:R('pf-cost2').value,supplier:R('pf-supplier2').value,notes:R('pf-notes2').value};if(!b.name)return toast('Nome é obrigatório','err');try{const r=id?await API.put(`/parts/${id}`,b):await API.post('/parts',b);const pid=id||r.id;const file=R('pf-photo2').files[0];if(file)await API.upload(`/uploads/parts/${pid}`,file);closeModal();toast('Salvo!');pageRenderers.pecas()}catch(e){toast(e.message,'err')}}
async function deletePeca(id){if(!confirmAction('Excluir esta peça?'))return;try{await API.del(`/parts/${id}`);pageRenderers.pecas()}catch(e){toast(e.message,'err')}}
function openPecaMov(id,name){openModal(`Movimentação — ${name}`,`<div class="form-grid"><div class="form-group"><label>Tipo</label><select id="pm-type"><option value="ENTRADA">Entrada</option><option value="SAIDA">Saída</option><option value="DEVOLUCAO">Devolução</option></select></div><div class="form-group"><label>Quantidade</label><input type="number" id="pm-qty" value="1" step="0.01"></div><div class="form-group span2"><label>Motivo</label><input id="pm-reason" value="AJUSTE"></div><div class="form-group span2"><label>Observações</label><textarea id="pm-notes"></textarea></div></div>`,`<button class="btn btn-secondary" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="savePecaMov(${id})">Registrar</button>`)}
async function savePecaMov(id){try{await API.post(`/parts/${id}/movement`,{type:R('pm-type').value,quantity:R('pm-qty').value,reason:R('pm-reason').value,notes:R('pm-notes').value});closeModal();toast('Movimentação registrada');pageRenderers.pecas()}catch(e){toast(e.message,'err')}}

window.savePecaMov=savePecaMov;
